/**
 * 金融级中英文标准对照词典
 */

export const CHINESE_NAME_MAP = {
  // === bStocks 美股与 Pre-IPO 独角兽 ===
  'SPACEXB': 'SpaceX 太空探索',
  'SPCXB': 'SpaceX 太空探索',
  'SANDKB': 'SanDisk 闪迪存储',
  'SNDKB': 'SanDisk 闪迪存储',
  'GLWB': '康宁玻璃科技 Corning',
  'OPENAIB': 'OpenAI 人工智能',
  'STARLINKB': '星链全球互联 Starlink',
  'BYDANDB': '字节跳动 ByteDance',
  'ANTHROPICB': 'Anthropic 克劳德 AI',
  'STRIPEB': 'Stripe 全球数字支付',
  'NEURALINKB': '脑机接口 Neuralink',
  'XAIB': 'xAI 人工智能 (Grok)',
  'ANDURILB': '安杜里尔 Anduril 国防科技',
  'DATABRICKSB': '数据湖仓 Databricks',
  'FIGMAb': 'Figma 协同设计',
  'FIGMAB': 'Figma 协同设计',
  'DISCORDB': 'Discord 游戏社群',
  'EPICB': 'Epic Games 虚幻引擎',
  'KRAKENB': 'Kraken 加密交易所',
  'SCALEAIB': 'Scale AI 数据标注',
  'GOOGLB': '谷歌 Alphabet (Google)',
  'MSFTB': '微软 Microsoft',
  'AAPLB': '苹果 Apple',
  'TSLAB': '特斯拉 Tesla',
  'NVDAB': '英伟达 NVIDIA',
  'METAB': 'Meta 脸书',
  'AMZNB': '亚马逊 Amazon',
  'ARMB': '安谋 ARM 芯片',
  'PLTRB': '帕兰提尔 Palantir 大数据',
  'COINB': 'Coinbase 交易所',
  'MSTRB': '微策略 MicroStrategy',
  'BABAB': '阿里巴巴 Alibaba',
  'TSMB': '台积电 TSMC',
  'MUB': '美光科技 Micron',
  'SPYB': '标普500 ETF (S&P 500)',
  'QQQB': '纳斯达克100 ETF (Nasdaq)',
  'HOODB': '罗宾汉 Robinhood',
  'CRCLB': 'Circle 稳定币发行商',
  'IBMB': '国际商业机器 IBM',
  'DRAMB': 'DRAM 存储芯片',
  'IRENB': '艾里斯能源 Iris Energy',
  'MVLLB': '美满电子 Marvell 2X',
  'KORUB': '韩国3倍多 ETF',
  'TQQQB': '纳指3倍做多 ETF',
  'MUUB': '微芯科技 Microchip',
  'BMNRB': '比特矿业 BitMine',
  'SNXXB': '半导体 2X 多头',
  'FLNCB': 'Fluence 储能科技',
  'NOKB': '诺基亚 Nokia',

  // === 现货主流与热门代币 (Spot) ===
  'BTC': '比特币 Bitcoin',
  'ETH': '以太坊 Ethereum',
  'BNB': '币安币 BNB',
  'SOL': '索拉纳 Solana',
  'DOGE': '狗狗币 Dogecoin',
  'PEPE': '佩佩蛙 Pepe',
  'SUI': 'Sui 高性能公链',
  'APT': 'Aptos 移动公链',
  'XRP': '瑞波币 Ripple',
  'ADA': '艾达币 Cardano',
  'AVAX': '雪崩协议 Avalanche',
  'LINK': '链节 Chainlink',
  'SHIB': '柴犬币 Shiba Inu',
  'NEAR': 'Near 协议',
  'DOT': '波卡 Polkadot',
  'TRX': '波场 Tron',
  'UNI': 'Uniswap 去中心化交易',
  'LTC': '莱特币 Litecoin',
  'BCH': '比特现金 Bitcoin Cash',
  'FET': '人工智能联盟 FET',
  'RENDER': 'Render 渲染网络',
  'TAO': 'Bittensor 去中心化AI',
  'WIF': '戴帽狗 dogwifhat',
  'BONK': '邦克犬 Bonk',
  'FIL': '文件币 Filecoin',
  'ARB': 'Arbitrum 二层公链',
  'OP': 'Optimism 二层网络',
  'TIA': 'Celestia 模块化公链',
  'SEI': 'Sei 高速公链',
  'INJ': 'Injective 衍生品公链',
  'JUP': 'Jupiter 聚合交易',
  'ENA': 'Ethena 合成美元',
  'ONDO': 'Ondo 现实世界资产 RWA',
  'PENDLE': 'Pendle 收益代币化',
  'FLOKI': 'Floki 社区模因币',
  'NOT': 'Notcoin 游戏点赚币',
  'TON': 'Telegram 开放网络 TON',
  'KAS': 'Kaspa 工作量证明公链',
  'STX': 'Stacks 比特币二层',
  'AAVE': 'Aave 借贷协议',
  'MKR': 'MakerDAO 稳定币协议',
  'ORDI': 'Ordinals 铭文龙头',
  'SATS': 'Sats 聪铭文',
  'RATS': 'Rats 老鼠铭文',
  'WLD': '世界币 Worldcoin',
  'ARKM': 'Arkham 链上情报分析',
  'CFX': 'Conflux 树图公链',
  'BOME': '模因书 Book of MEME',
  'POPCAT': '爆米花猫 Popcat',
  'MEW': '猫咪世界 MEW',
  'NEIRO': '小狗狗 Neiro',
  'TURBO': 'Turbo 人工智能 Meme',
  '1000SATS': 'Sats 聪铭文',
  '1000RATS': 'Rats 老鼠铭文',
  '1000CAT': 'Cat 模因币',
  '1000CHEEMS': 'Cheems 柴犬模因'
};

export function getChineseDisplayName(sym, rawName, ticker) {
  if (!sym) return rawName || '';
  const clean = String(sym).toUpperCase().replace(/(USDT|\/USDT)$/i, '').replace(/[^A-Z0-9]/g, '');
  if (CHINESE_NAME_MAP[clean]) return CHINESE_NAME_MAP[clean];
  
  if (clean.endsWith('B') && CHINESE_NAME_MAP[clean.slice(0, -1)]) {
    return CHINESE_NAME_MAP[clean.slice(0, -1)] + ' (bStocks)';
  }
  
  return rawName || ticker || clean;
}
